version: 2

jobs:
  server_test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: install package
          command: yarn install
      - run:
          name: test
          command: yarn test
  build_docker_image:
    environment:
      DOCKER_IMAGE_NAME: hello_world_ts
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: decode pre-environment data to json file.
          command: echo $GCLOUD_SERVICE_KEY | base64 --decode > /tmp/gcloud-key.json
      - run:
          name: authenticate with json key file.
          command: |
            gcloud auth activate-service-account --key-file /tmp/gcloud-key.json
            gcloud --quiet config set project $GCP_PROJECT_ID
            gcloud --quiet config set compute/zone asia-southeast1-a
      - run:
          name: authenticate docker for pushing image
          command: |
            gcloud auth configure-docker
      - run:
          name: build docker image
          command: docker build -t $DOCKER_IMAGE_NAME .
      - run:
          name: add a docker tag to local image
          command: |
            docker tag \
            $DOCKER_IMAGE_NAME:latest \
            gcr.io/$GCP_PROJECT_ID/$DOCKER_IMAGE_NAME:$CIRCLE_SHA1
      - run:
          name: push image
          command: docker push gcr.io/$GCP_PROJECT_ID/$DOCKER_IMAGE_NAME:$CIRCLE_SHA1
  deploy_to_k8s:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: decode pre-environment data to json file.
          command: echo $GCLOUD_SERVICE_KEY | base64 --decode > /tmp/gcloud-key.json
      - run:
          name: authenticate with json key file.
          command: |
            gcloud auth activate-service-account --key-file /tmp/gcloud-key.json
            gcloud --quiet config set project $GCP_PROJECT_ID
            gcloud --quiet config set compute/zone asia-southeast1-a
            gcloud --quiet container clusters get-credentials test-cluster
      - run:
          name: apply deployment and service
          command: |
            kubectl --insecure-skip-tls-verify apply -f ./deployment.yml
            kubectl rollout status deployment/hello_world_ts
      
workflows:
  version: 2
  build-master:
    jobs:
      - server_test:
          filters:
            branches:
              only: master
      - build_docker_image:
          context: gcloud credential
          requires:
            - server_test
          filters:
            branches:
              only: master
      - deploy_to_k8s:
          context: gcloud credential
          requires:
            - build_docker_image
          filters:
            branches:
              only: master