version: 2.1

jobs:
  server_test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: install package
          command: yarn install
      - run:
          name: test
          command: yarn test
  build_docker_image:
      environment:
        DOCKER_IMAGE_NAME: hello_world_ts
      docker:
        - image: circleci/node
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: build docker image
            command: docker build -t $DOCKER_IMAGE_NAME .
        - run:
            name: login to docker hub
            command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        - run:
            name: add a docker tag to local image
            command: docker tag $DOCKER_IMAGE_NAME:latest willpower/$DOCKER_IMAGE_NAME:latest
        - run:
            name: push image
            command: docker push willpower/$DOCKER_IMAGE_NAME:latest

workflows:
  version: 2
  build-master:
    jobs:
      - server_test:
          filters:
            branches:
              only: master
      - build_docker_image:
          context: docker credential
          requires:
            - server_test
          filters:
            branches:
              only: master