version: 2.1

jobs:
  server_test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: install package
          command: yarn install
      - run:
          name: test
          command: yarn test
  build_docker_image:
      docker:
        - image: circleci/node
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: build docker image
            command: docker build -t hello-world-ts .
        - run:
            name: login to docker hub
            command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        - run:
            name: push image
            command: docker push willpower/hello-world-ts:latest

workflows:
  version: 2.1
  build-master:
    jobs:
      - server_test:
          filters:
            branches:
              only: master
      - build_docker_image:
          context: docker credential
          requires:
            - server_test
          filters:
            branches:
              only: master