version: 2.1

orbs:
  gcp-gke: circleci/gcp-gke@0.1.0

jobs:
  server_test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: install package
          command: yarn install
      - run:
          name: test
          command: yarn test
  build_docker_image:
      environment:
        DOCKER_IMAGE_NAME: hello_world_ts
      docker:
        - image: google/cloud-sdk
      steps:
        - checkout
        - run:
            name: decode pre-environment data to json file.
            command: echo $GCLOUD_SERVICE_KEY | base64 --decode > /tmp/gcloud-key.json
        - run:
            name: authenticate with json key file.
            command: |
              gcloud auth activate-service-account --key-file /tmp/gcloud-key.json
              gcloud config set project $GCP_PROJECT_NAME
              gcloud config set compute/zone asia-southeast1-a
        - run:
            name: build docker image
            command: gcloud docker build -t $DOCKER_IMAGE_NAME .
        - run:
            name: get version from package.json
            command: |
              export PACKAGE_VERSION=$( \
              cat package.json | \
              grep version | \
              cut -d " " -f 4 | \
              sed 's/[",]//g')
        - run:
            name: add a docker tag to local image
            command: |
              gcloud docker tag \
              $DOCKER_IMAGE_NAME:latest \
              gcr.io/$GCP_PROJECT_NAME/hello-world-ts:$PACKAGE_VERSION
        - run:
            name: push image
            command: gcloud docker push gcr.io/$GCP_PROJECT_NAME/hello-world-ts:$PACKAGE_VERSION

workflows:
  version: 2
  build-master:
    jobs:
      - server_test:
          filters:
            branches:
              only: master
      - build_docker_image:
          context: gcloud credential
          requires:
            - server_test
          filters:
            branches:
              only: master